In [1]:
from mindex_bengals import get_bengals_data, load_data_to_database, view_bengals_data_in_db, run_test_query

In [2]:
begnals_data = get_bengals_data()

In [3]:
begnals_data

,Week,Opponent,Location,Result,Yards Boyd,Yards Chase,Yards Higgins,TD Boyd,TD Chase,TD Higgins
0,PRE1,TB,Away,Win,0.0,0.0,0.0,0.0,0.0,0.0
1,PRE2,WSH,Away,Loss,0.0,0.0,0.0,0.0,0.0,0.0
2,PRE3,MIA,Home,Loss,0.0,0.0,0.0,0.0,0.0,0.0
3,REG1,MIN,Home,Win,32.0,101.0,58.0,0.0,1.0,1.0
4,REG2,CHI,Away,Loss,73.0,54.0,60.0,0.0,1.0,1.0
5,REG3,PIT,Away,Win,36.0,65.0,0.0,1.0,2.0,0.0
6,REG4,JAX,Home,Win,118.0,77.0,0.0,0.0,0.0,0.0
7,REG5,GB,Home,Loss,24.0,159.0,32.0,0.0,1.0,0.0
8,REG6,DET,Away,Win,7.0,97.0,44.0,0.0,0.0,0.0
9,REG7,BAL,Away,Win,39.0,201.0,62.0,0.0,1.0,0.0
10,REG8,NYJ,Away,Loss,69.0,32.0,97.0,1.0,1.0,0.0
11,REG9,CLE,Home,Loss,11.0,49.0,78.0,0.0,0.0,0.0
13,REG11,LV,Away,Win,49.0,32.0,15.0,0.0,1.0,0.0
14,REG12,PIT,Home,Win,13.0,39.0,114.0,0.0,0.0,1.0
15,REG13,LAC,Home,Loss,85.0,52.0,138.0,0.0,0.0,1.0
16,REG14,SF,Home,Loss,55.0,77.0,114.0,0.0,2.0,0.0
17,REG15,DEN,Away,Win,96.0,3.0,23.0,1.0,0.0,0.0
18,REG16,BAL,Home,Win,85.0,125.0,194.0,1.0,0.0,2.0
19,REG17,KC,Home,Win,36.0,266.0,62.0,1.0,3.0,0.0
20,REG18,CLE,Away,Loss,0.0,26.0,0.0,0.0,0.0,0.0
21,POST1,LV,Home,Win,26.0,116.0,10.0,1.0,0.0,0.0
22,POST2,TEN,Away,Win,17.0,109.0,96.0,0.0,0.0,0.0
23,POST3,KC,Away,Win,19.0,54.0,103.0,0.0,1.0,0.0
24,POST4,LAR,Neutral,Loss,48.0,89.0,100.0,0.0,0.0,2.0

In [4]:
load_data_to_database = load_data_to_database(dataframe=begnals_data, table_name='drew_ringo')

In [1]:
view_bengals_data_in_db(table_name='drew_ringo')

NameError: name 'view_bengals_data_in_db' is not defined

In [2]:
run_test_query()

   Boyd Yards  Higgins Yards  Chase Yards Win/Loss
0       938.0         1400.0       1823.0    14-10